### ISSUE TITLE
Inconsistency in "stakingoptions" RPC

### ISSUE THREAD

**Issue by glemercier** [Bitcoin-Confidential/BitcoinC-Core#1]
In the following piece of code: 

https://github.com/Bitcoin-Confidential/BitcoinC-Core/blob/24b307dbf876c3aa57197a8491d11380751aa7b8/src/wallet/hdwallet.cpp#L345-L348

The error states `stakecombinethreshold` should be higher than 10000 but is tested against 100000. This yields to the user not understanding what is actually wrong in the provided values.

**Comment by xdustinface** [comment]
Thanks for reporting. Fixed it, will be included in the next release.
