### ISSUE TITLE
Add onion network option in options

### ISSUE THREAD

**Issue by deyvisonrocha** [Bitcoin-Confidential/BitcoinC-Core#2]
Why not put the Tor network option on the options screen inside the wallet?

**Comment by ArcherBullseye** [comment]
When you say 'in the wallet' are you thinking in like
Settings > Options > Network?

**Comment by deyvisonrocha** [comment]
> When you say 'in the wallet' are you thinking in like
> Settings > Options > Network?

Exactly.

**Comment by thesolarminer** [comment]
Possible to do.  I think we would also include IPV4 and IPV6 options with that change.  Appreciate the suggestion.

**Comment by deyvisonrocha** [comment]
We are together!
