### ISSUE TITLE
My Bitcoin Confidential Core Wallet is not syncing

### ISSUE THREAD

**Issue by alexp301989** [Bitcoin-Confidential/BitcoinC-Core#5]
My Bitcoin Confidential Core Wallet has not synced in almost a month.
 Regular start up of my digital wallet with all my contents in place.

 It will not complete syncing and says its connecting to peers and it also states that my peers is banned.

 It happens everytime I try to load up my application.

 I am using V1.0.3 and I downloaded it from Github.com

 Windows 10 Standard disk drive

 I have not linked my digital wallet with any other wallets, I have only deposited cryptocurrency into my wallet.
![Screenshot (13)](https://user-images.githubusercontent.com/79957840/123546366-4b7ccb00-d72a-11eb-9664-0a043bdf9aea.png)
![Screenshot (14)](https://user-images.githubusercontent.com/79957840/123546367-4c156180-d72a-11eb-982a-9c3101133d21.png)
![Screenshot (15)](https://user-images.githubusercontent.com/79957840/123546368-4c156180-d72a-11eb-8b81-2a839a1af251.png)
![Screenshot (16)](https://user-images.githubusercontent.com/79957840/123546369-4c156180-d72a-11eb-9306-43a28a44f37c.png)
![Screenshot (17)](https://user-images.githubusercontent.com/79957840/123546370-4c156180-d72a-11eb-8e6f-b776c6955cce.png)
![Screenshot (18)](https://user-images.githubusercontent.com/79957840/123546371-4cadf800-d72a-11eb-8a5e-3ae72bddc77f.png)
![Screenshot (19)](https://user-images.githubusercontent.com/79957840/123546372-4cadf800-d72a-11eb-89bd-fbe32f7d5df6.png)
![Screenshot (20)](https://user-images.githubusercontent.com/79957840/123546373-4cadf800-d72a-11eb-9599-0c4d86a2b898.png)
![Screenshot (21)](https://user-images.githubusercontent.com/79957840/123546374-4d468e80-d72a-11eb-9450-3526478ca838.png)
![Screenshot (22)](https://user-images.githubusercontent.com/79957840/123546375-4d468e80-d72a-11eb-8e0e-db9e8c562fb7.png)
![Screenshot (23)](https://user-images.githubusercontent.com/79957840/123546376-4d468e80-d72a-11eb-8d66-e51bc02d44ce.png)
![Screenshot (24)](https://user-images.githubusercontent.com/79957840/123546377-4ddf2500-d72a-11eb-8e32-9baf46794a63.png)
![Screenshot (25)](https://user-images.githubusercontent.com/79957840/123546378-4ddf2500-d72a-11eb-9b9e-6170e3cf9aa8.png)
![Screenshot (26)](https://user-images.githubusercontent.com/79957840/123546380-4e77bb80-d72a-11eb-936d-b38ce5d45cec.png)
![Screenshot (27)](https://user-images.githubusercontent.com/79957840/123546381-4e77bb80-d72a-11eb-9057-61b8a0d753e1.png)
![Screenshot (28)](https://user-images.githubusercontent.com/79957840/123546382-4e77bb80-d72a-11eb-94b1-8fe28908f9a3.png)
![Screenshot (29)](https://user-images.githubusercontent.com/79957840/123546383-4f105200-d72a-11eb-9563-8263967f1ba2.png)
![Screenshot (48)](https://user-images.githubusercontent.com/79957840/123546398-5899ba00-d72a-11eb-88af-33e1adf2cf1b.png)
![Screenshot (50)](https://user-images.githubusercontent.com/79957840/123546402-5cc5d780-d72a-11eb-8700-be0018926dc9.png)

**Comment by thesolarminer** [comment]
You need to reindex.  You can select from the wallet tools menu or use the guide to remove old blocks.  Here is the guide.
https://bitcoinconfidential.freshdesk.com/support/solutions/articles/44001672644-my-wallet-crashed-or-not-synced-how-to-resolve-

**Comment by alexp301989** [comment]
Yes! After conducting the running load test on my computer and following
the steps outlined here for reindex, my wallet is up and running again and
I was able to fully update my work. This is great.

**Comment by thesolarminer** [comment]
Glad I could help.
